### ISSUE TITLE
Support GHC 8

### ISSUE THREAD

**Issue by swiftvimla** [lambdacube3d/lambdacube-compiler#17]

**Comment by csabahruska** [comment]
Which GHC version of the 8.x series?
The current code does compile with GHC 8.6.1.
It is used in lambdacube-quake3 project:
https://github.com/lambdacube3d/lambdacube-quake3/blob/master/stack.yaml

Is it a problem that lambdacube-compiler's stack.yaml relies on an older version of stackage lts?

**Comment by swiftvimla** [comment]
Yes, the resolver seems to be a problem. I've had to clone all the lambdacube repos (gl/ir/compiler) and fiddle with the project settings to make them jive with GHC 8.

Thanks for the quick reply!

**Comment by csabahruska** [comment]
You do not have to clone the repositories to use lambdacube libraries with GHC 8.
The only thing you need is a local `stack.yaml` for your GHC 8 project just like lambdacube-quake3 does and refer the required lambdacube github repositories.
https://github.com/lambdacube3d/lambdacube-quake3/blob/master/stack.yaml#L10-L22

What is the problem with this method?
It should not be an overhead. I guess your project has a `stack.yaml` also just like lambdacube-quake3.

**Comment by swiftvimla** [comment]
It does have a `stack.yaml` file. I believe I tried your approach initially (a few days ago). Running into an issue with stack not being able to handle archives properly.

`Archive extraction failed. Tarballs and zip archives are supported, couldn't handle the following URL, [...]`

**Comment by csabahruska** [comment]
Did it work?

**Comment by csabahruska** [comment]
I'm closing this issue because GHC 8 is supported.
Lambdacube can be used in a stack (1.9.3) project with the following `stack.yaml` syntax:
```
packages:
- location:
    git: https://github.com/lambdacube3d/lambdacube-ir.git
    commit: b8b4ec9fa985b2eb756ac1a5a65af483a0bd586b
  subdirs:
    - lambdacube-ir.haskell
  extra-dep: true
- location:
    git: https://github.com/lambdacube3d/lambdacube-gl.git
    commit: 297828bdcf105c5942ed0e43d9f28130f543f34c
  extra-dep: true
- location:
    git: https://github.com/lambdacube3d/lambdacube-compiler.git
    commit: dc10dc255638b86f4a20a29a1b492e2415640b60
extra-dep: true
```

If the newer/simpler `github: ...` syntax does not work for `stack.yaml` then it is probably a stack bug.
